// misc
export const MAIN_COLOR = '#5B3C88';

// storage
export const STORAGE_FONTSIZE = 'STORAGE_FONTSIZE';

// actions
export const SET_GLOBAL_FONTSIZE = 'SET_GLOBAL_FONTSIZE';
export const CHANGE_SIDEDRAWER_OPENER_ID = 'CHANGE_SIDEDRAWER_OPENER_ID';
